language: r
cache: packages
sudo: true

# only run for pushes to master branch
branches:
  only:
   - master

r_github_packages:
  - r-lib/covr
  - r-lib/testthat

env:
  - PKG_TARBALL=clustcurv_2.0.1.1000.tar.gz

after_success:
  - tar -C .. -xf $PKG_TARBALL
      - xvfb-run Rscript -e 'covr::codecov()'

warnings_are_errors: true

notifications:
  slack:
    rooms:

    on_success: change # default: always
    on_failure: always # default: always

script:
  - R CMD check *tar.gz --as-cran
